spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Lucene
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./data/index

        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

